name = "LSpec"
version = "2.0.0"
defaultTargets = ["LSpec"]
testDriver = "tests"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "6304553"

[[lean_lib]]
name = "LSpec"

[[lean_exe]]
name = "tests"
root = "Tests.Main"
